# Generated by Django 5.1.2 on 2025-04-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthprogram',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='interests',
            field=models.TextField(blank=True),
        ),
    ]
