# Generated by Django 5.1.2 on 2025-04-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
