# Generated by Django 5.1.2 on 2025-04-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprogram',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprogram',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
