# Generated by Django 5.1.2 on 2025-04-26 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_healthprogram_description_healthprogram_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='program',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.healthprogram'),
            preserve_default=False,
        ),
    ]
